## Adding, removing, and sorting elements

In [5]:
import numpy as np

### Adding Data

#### Append

In [4]:
arr = np.arange(10)
print(arr)

np.append(arr,[10,11,12])

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When axis is specified, values must have the correct shape. 
* `axis` `0` = `rows` 
* `axis` `1` = `column`

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

np.append(arr1,[[10,12,13]], axis=0)

[[1 2 3]
 [4 5 6]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 12, 13]])

####  Concatenate
if axis = None, then arrays are flatten before use

In [6]:
a = np.array([[1, 2, 8], [5, 8, 10]])
b = np.array([[8, 2, 1], [3, 9, 1]])
c = np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  8],
       [ 5,  8, 10],
       [ 8,  2,  1],
       [ 3,  9,  1]])

In [12]:
x = np.array([[1,2,3], [1,1,1]])
y = np.array([[3,3,1], [1,2,3]])
z = np.concatenate((x,y), axis=1)
z

array([[1, 2, 3, 3, 3, 1],
       [1, 1, 1, 1, 2, 3]])

####  Delete
np.delete(`variable array`, `index array`, `axis`)

In [4]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f'Before delete\n{arr}')

np.delete(arr, 1, axis=1)

Before delete
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

#### Sorting

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(f'before sort : {arr}')

print('after sort :',np.sort(arr))

before sort : [2 1 5 3 7 4 6 8]
after sort : [1 2 3 4 5 6 7 8]


## Shape and Size of an array

* `ndarray.ndim` : the number of axis *(`rows`,`columns`,`depth`)* \
* `ndarray.size` : the total number of element \
* `ndarray.shape`: the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [23]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])
my_array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [26]:
print(f'shape : {my_array.shape}')
print(f'size  : {my_array.size}')
print(f'ndim  : {my_array.ndim}')

shape : (3, 2, 4)
size  : 24
ndim  : 3


## Reshaping an array

When you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [35]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

## Exercise 3

1. create a 3x3 matrix with values ranging from 2 to 10

In [38]:
m = np.arange(2,11)
print(m)
m.reshape(3,3)

[ 2  3  4  5  6  7  8  9 10]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](../image/lat3.png)

In [6]:
x = np.array([[0,1,3],
              [5,7,9]])

y = np.array([[0,2,4],
              [6,8,10]])

result = np.concatenate((x, y), axis=1)
result

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

## Converting a 1D array into 2D array (add a new axis to an array)

You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array

`np.newaxis` will increase the dimension of array by one when it is used once. \
1D -> 2D, 2D -> 3D, and so on

In [7]:
a = np.array([1,2,3,4,5,6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [49]:
# convert a 1D array to a row vector by inserting an axis along the first dimension
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[1 2 3 4 5 6]]


(1, 6)

In [52]:
# for a column vector, you can insert an axis along the second dimension
a3 = a[1:5, np.newaxis]
print(a3)
a3.shape

[[2]
 [3]
 [4]
 [5]]


(4, 1)

using `np.expand_dims`

In [53]:
b = np.expand_dims(a, axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [54]:
# You can add an axis at index position 0 with
c = np.expand_dims(a, axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

In [24]:
data = np.array([[1,23,4],
                [2,3,4]])
res = np.expand_dims(data,axis=0)
print(data)
print(f'\ndata shape : {data.shape}\n')
print(res)
print(f'\nres shape : {res.shape}')

[[ 1 23  4]
 [ 2  3  4]]

data shape : (2, 3)

[[[ 1 23  4]
  [ 2  3  4]]]

res shape : (1, 2, 3)


## Indexing and Slicing

In [60]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
# choose index 3 from array
data[3]

3

In [63]:
# choose first index untill before index 5
data[:5]

array([0, 1, 2, 3, 4])

In [64]:
# choose index 3 till last
data[3:]

array([3, 4, 5, 6, 7])

In [66]:
# choose index -2 or number 2 before last
data[-2]

6

In [68]:
# choose data from index 2 to index 5
data[2:6]

array([2, 3, 4, 5])

![](../image/numpy.jpg)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [69]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [70]:
a[a<5]

array([1, 2, 3, 4])

You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [73]:
print(a[a>=5])

# check with boolean
five_up = a >= 5
five_up

[ 5  6  7  8  9 10 11 12]


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
d = a[a % 2 == 0 ]
d

array([ 2,  4,  6,  8, 10, 12])

Or you can select elements that satisfy two conditions using the & and | operators:

In [76]:
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [77]:
print(a)

# select row 1, index 1 till index 2
a[1,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([6, 7])

In [7]:
z = np.array([[[0, 1, 3],
               [5, 7, 9]],
              
              [[0, 2, 4],
               [6, 8, 10]]])
print(z)
z.shape

[[[ 0  1  3]
  [ 5  7  9]]

 [[ 0  2  4]
  [ 6  8 10]]]


(2, 2, 3)

In [79]:
# access row 0
z[0]

array([[0, 1, 3],
       [5, 7, 9]])

In [80]:
# access row 0, column 1
z[0,1]

array([5, 7, 9])

In [8]:
# access rows 0, column 1, depth 1-last
z[0,1,1:]

array([7, 9])

In [83]:
a = np.array([1,31,1,4,5,2,1])
a

array([ 1, 31,  1,  4,  5,  2,  1])

In [84]:
# access index 1 till 3
a[1:4]

array([31,  1,  4])

## Exercise 4

1. create a null vector / 1D array of size 10 and update fifth index to 11.

In [90]:
x = np.zeros(10)
x[5] = 11
print(x)
x.size

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


10

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [101]:
number2 = np.ones((2,3))
print(f'shape before {number2.shape}')

result = number2.reshape(3,2)
result.shape

shape before (2, 3)


(3, 2)

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](../image/lat1.png)

In [28]:
x = np.ones((5,5), dtype=float)
print(x)

# x[1:4,1:4] = 0
x[1:-1,1:-1] = 0
x

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

4. Take a look at the following matrix. Access the [2, 1, 1]

In [29]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

print(z[2,1,1])

2


## Creating an array from existing data

You can easily use create a new array from a section of an existing array.

In [123]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [125]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

using `vstack`

In [126]:
# vertical
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

using `hstack`

In [127]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using `hsplit`. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [31]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [32]:
y = np.hsplit(x,3)
y

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you want to split your array after the third and fourth column, you’d run:

In [33]:
z = np.hsplit(x,(3,5)) # 0:3, 3:5, 5:
print(x)
z

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [14]:
m = np.hsplit(x, (1,3,6)) # 0:1, 1:3, 3:6, 6:
m

[array([[ 1],
        [13]]),
 array([[ 2,  3],
        [14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

## Basic array operations

In [20]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print('data', data)
print('ones', ones)

data [1 2]
ones [1 1]


In [19]:
data + ones

array([2, 3])

![](../image/np_data_plus_ones.png)

In [21]:
data * data

array([1, 4])

In [22]:
data / data

array([1., 1.])

In [23]:
a = np.array([1,2,3,4])
a.sum() # calculate all element

10

sum the rows/columns

In [36]:
b = np.array([[1,1],
              [5,2]])

print('sum :',b.sum())
print('sum row :', b.sum(axis=0)) # sum elements rows
print('sum column :', b.sum(axis=1)) # sum elements column

sum : 9
sum row : [6 3]
sum column : [2 7]


## Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [32]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

![](../image/np_multiply_broadcasting.png)

NumPy understands that the multiplication should happen with each cell. That concept is called <b> broadcasting </b>. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

## Working with Mathematical Formulas

The ease of implementing mathematical formulas that work on arrays is one of the things that make NumPy so widely used in the scientific Python community.

![](../image/np_MSE_formula.png)

In [36]:
n = 3
y_pred = np.array([1,1,1])
labels = np.array([1,2,3])
mse = (1/n) * np.sum(np.square(y_pred - labels))
mse

1.6666666666666665

![](../image/np_mse_viz1.png)

![](../image/np_mse_viz2.png)

## How to save and load NumPy objects?

The ndarray objects can be saved to and loaded from the disk files with `loadtxt` and `savetxt` functions that handle normal text files, `load` and `save` functions that handle NumPy binary files with a .npy file extension, and a `savez` function that handles NumPy files with a .npz file extension.

If you want to store a single ndarray object, store it as a .npy file using np.save. If you want to store more than one ndarray object in a single file, save it as a .npz file using `np.savez`. You can also save several arrays into a single file in compressed npz format with `savez_compressed`.

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])

In [38]:
np.save('myfile',a) # save variable a with name "myfile"

In [39]:
# load file
b = np.load('myfile.npy')
b

array([1, 2, 3, 4, 5, 6])

You can save a NumPy array as a plain text file like a .csv or .txt file with `np.savetxt`.

In [40]:
csv_arr = np.array([[1,23,4,5],
                    [2,5,6,7]])

In [46]:
np.savetxt('myfile2.csv',csv_arr)

In [42]:
np.loadtxt('myfile2.csv')

array([[ 1., 23.,  4.,  5.],
       [ 2.,  5.,  6.,  7.]])

# ASSIGNMENT

1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](../image/assignment2.png)

In [39]:
a = np.zeros((4,4))
a[:,1:] = [1,2,3]
print(a)
print('\nshape :',a.shape)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]

shape : (4, 4)


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](../image/assignment.png)

In [107]:
y = np.arange(16).reshape(4,4)
print(y,'\n')

result = np.hsplit(y,2)
for i in result:
    print(i,'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 

