# NUMPY - Multidimensional Data Arrays

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use.

In [2]:
import numpy as np

In [26]:
# check version
np.__version__

'1.20.1'

In [28]:
# check documentation
np.info(np.reshape)

 reshape(a, newshape, order='C')

Gives a new shape to an array without changing its data.

Parameters
----------
a : array_like
    Array to be reshaped.
newshape : int or tuple of ints
    The new shape should be compatible with the original shape. If
    an integer, then the result will be a 1-D array of that length.
    One shape dimension can be -1. In this case, the value is
    inferred from the length of the array and remaining dimensions.
order : {'C', 'F', 'A'}, optional
    Read the elements of `a` using this index order, and place the
    elements into the reshaped array using this index order.  'C'
    means to read / write the elements using C-like index order,
    with the last axis index changing fastest, back to the first
    axis index changing slowest. 'F' means to read / write the
    elements using Fortran-like index order, with the first index
    changing fastest, and the last index changing slowest. Note that
    the 'C' and 'F' options take no account of the me

# What is Array

![](../image/array.png)

In [37]:
# List Python
a = [1,2,3,4]
b = [5,6,7,8]

print(f"{a}, type : {type(a)}")
print(f"{b}, type : {type(b)}")

[1, 2, 3, 4], type : <class 'list'>
[5, 6, 7, 8], type : <class 'list'>


In [38]:
# Operation
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can't multiply sequence by non-int of type 'list'

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 


Create an array with `numpy` using *np.array*

In [40]:
a_array = np.array(a)
b_array = np.array(b)

print(f"{a_array}, type : {type(a_array)}")
print(f"{b_array}, type : {type(b_array)}")

[1 2 3 4], type : <class 'numpy.ndarray'>
[5 6 7 8], type : <class 'numpy.ndarray'>


In [41]:
# Operations
print(a_array + b_array)
print(a_array / b_array)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


## Creating `numpy` arrays

There are some ways to initialize new numpy arrays:
* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

**Parameters for array** `(row, column, depth)`

Type array : `numpy.ndarray`

In [5]:
# Vector (matrix one line)
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


In [6]:
# Matrix
m = np.array([[1,2,3],[5,6,7]])
print(m)

[[1 2 3]
 [5 6 7]]


Check ordo matrix using `shape` and `size` for number of elements in the array

In [45]:
print(v.shape)
print(v.size)

print(m.shape)
print(m.size)

(5,)
5
(2, 3)
6


In [46]:
type(v),type(m)

(numpy.ndarray, numpy.ndarray)

`numpy.ndarray` looks very similiar to the `list`. So, why not use the list instead?
`numpay.ndarray` is used for several reason:
1. Lists are very general. They can contain any kind of object. They do not support mathematical functions such as matrix and dot multiplication, etc. 
2. Numpy arrays are statically typed and homogenous. The type of the elements is determined when the array is created
3. Numpy arrays are memory efficient
4. It is fast for implementation of mathematical function

We can see the type of data of an array using `dtype`

In [47]:
v.dtype

dtype('int32')

Common data types that can be used with `dtype` : 
* `int`, 
* `float`, 
* `complex`, 
* `bool`, 
* `object`, 
* *etc.*

### Tugas:
1. membuat array 1 dimensi 7, 
2. membuat array 2 dimensi 3, 3
3. membuat array 3 dimensi 4, 4, 4

In [53]:
# Number 1
number_one = np.array([1,2,3,4,5,6,7])
print(number_one)
number_one.shape

[1 2 3 4 5 6 7]


(7,)

In [52]:
# Number 2
number_two = np.array([[3,1,2],
                       [5,6,1],
                       [6,5,6]])
print(number_two)
number_two.shape

[[3 1 2]
 [5 6 1]
 [6 5 6]]


(3, 3)

In [61]:
# Number 3
number_three = np.array([[[1,2,3,4],
                         [5,23,1,5],
                         [41,2,3,5],
                         [1,0,5,3]],
                        
                        [[1,2,5,6],
                         [2,3,5,5],
                         [3,2,1,3],
                         [0,0,0,1]],
                        
                        [[1,2,3,4],
                         [5,23,1,5],
                         [41,2,3,5],
                         [1,0,5,3]],
                         
                        [[1,2,3,4],
                         [5,23,1,5],
                         [41,2,3,5],
                         [1,0,5,3]]])
print(number_three)
number_three.shape

[[[ 1  2  3  4]
  [ 5 23  1  5]
  [41  2  3  5]
  [ 1  0  5  3]]

 [[ 1  2  5  6]
  [ 2  3  5  5]
  [ 3  2  1  3]
  [ 0  0  0  1]]

 [[ 1  2  3  4]
  [ 5 23  1  5]
  [41  2  3  5]
  [ 1  0  5  3]]

 [[ 1  2  3  4]
  [ 5 23  1  5]
  [41  2  3  5]
  [ 1  0  5  3]]]


(4, 4, 4)

### Create array with `1`  value using `ones`

In [95]:
ones = np.ones((2,3,4), dtype=int)


# Print ones
print(ones)
print(ones.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int32


If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument:

In [70]:
m = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=float)

print(m)

# check type of value
print(m.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


### Create array with `0`  value using `zeros`

In [81]:
# One Dimension
zeros_matrix = np.zeros(5)
print(zeros_matrix)

# for Two dimension or more should be in tuple format
# Two Dimension
zeros_matrix2 = np.zeros((3,3)) # 3 rows, 2 columns
print(f'\n{zeros_matrix2}')

# Three dimension
zeros_matrix3 = np.zeros((2,3,4)) # 2 row, 3 column, 4 depth
print(f'\n{zeros_matrix3}')

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


## Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [27]:
exercise_1 = np.array([[1,2,3],
                       [4,5,6],
                       [3,1,2],
                       [5,3,1]])

exercise_1.shape

(4, 3)

2. Create the following matrix
![](../image/lat11.png)

In [25]:
exercise_2 = np.array([[2,7,12,0],
                       [3,9,3,4],
                       [4,0,1,3]])
exercise_2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

3. Create a 2D matrix with size of 10 

In [24]:
# 2 rows 5 columns
exercise_3 = np.array([[1,2,3,4,5],
                       [3,1,6,7,8]])

print(exercise_3.shape)
print(exercise_3.size)

(2, 5)
10


In [23]:
# using method zeros
exercise_3 = np.zeros((2,5))

print(exercise_3.shape)
print(exercise_3.size)

(2, 5)
10


In [19]:
# 5 rows 2 columns
exercise_3 = np.array([[1,2],
                       [2,2],
                       [2,1],
                       [3,3],
                       [4,5]])

print(exercise_3.shape)
print(exercise_3.size)

(5, 2)
10


In [28]:
# 10 rows 1 columns
exercise_3 = np.array([[1],
                       [2],
                       [2],
                       [3],
                       [4],
                       [9],
                       [10],
                       [10],
                       [7],
                       [1]])

print(exercise_3.shape)
print(exercise_3.size)

(10, 1)
10


4. Create a 3d Matrix of ones which has 2 rows, 3 columns, 3 depth

In [30]:
exercise_4 = np.array([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],

                       [[6, 2, 3],
                        [4, 5, 8],
                        [8, 8, 9]]])

print(exercise_4.shape)
print(exercise_4.size)

(2, 3, 3)
18


5. Make the following arrays from zeros arrays and with for loops
![](../image/exercise1.png)

In [31]:
exercise_5 = np.zeros((5,3))
exercise_5.dtype

dtype('float64')

In [34]:
# using loop
for i in exercise_5:
    print(i+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


In [37]:
# without loop
exercise_5 + 2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

`arange`

In [97]:
# Create a range
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Create a range with arguments 
x = np.arange(10,20) # arguments : start, stop
print(x)

y = np.arange(10,20,2) # arguments : start, stop, step
print(y)

[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [99]:
x = np.arange(-1, 1, 0.1)

x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

The number 9.00000000e-01 already is a floating point number.
It's written in scientific notation and is equivalent to 9 * 10**-1 or 0.9.

`linspace`

using linspace, both end point are **included*

In [101]:
# Unlike arange that uses step, linspace uses the number of sample
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

`random data`

In [40]:
# library for random in numpy
from numpy import random

In [103]:
# uniform random numbers in [0,1]
random.rand(1,5)

array([[0.33923281, 0.36027279, 0.80905422, 0.02240745, 0.56790409]])

In [109]:
# standard normal distributed random numbers
x = random.randn(1,10)
x

array([[ 0.55865286,  0.07948305,  0.40999036,  0.0076045 , -0.65078891,
        -0.45918335,  0.2712651 , -1.13099664,  1.28812305, -0.25309684]])

In [110]:
x.dtype

dtype('float64')

In [117]:
x = np.ones((5,3), dtype = np.int64)
print(x)
x

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [120]:
# random data type int
random.randint(10)

6

In [124]:
# make array with random int
random.randint(2,10, size=4) # random from 2 to 10 with 4 column

array([5, 2, 7, 7])

In [41]:
# random from 2 to 10 with 4 rows, 2 columns, 2 depth
random.randint(2,10, size=(4,2,2))

array([[[4, 2],
        [9, 3]],

       [[5, 6],
        [6, 9]],

       [[9, 7],
        [9, 2]],

       [[6, 7],
        [8, 8]]])

## Exercise 2

1. Generate a 1D array containing 5 random integers from 0 to 100:

In [126]:
random.randint(0,100, size=5)

array([52, 10,  3, 73, 98])

2. Generate a 2D array with 3 rows, each row contains 5 random integers from 0 to 100

In [127]:
random.randint(0,100, size=(3,5))

array([[56, 99, 13, 87, 74],
       [21,  4, 20,  2, 62],
       [46, 86, 10, 75, 55]])

3. Generate a 1D array of 30 evenly spaced elements between 1.5 and 5.5, `inclusive.`

In [128]:
np.linspace(1.5,5.5,30)

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])